[2025-05-24T04:38:15.123+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-24T04:38:15.150+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: order_monitoring_dag1.run_dbt_models scheduled__2025-05-23T22:00:00+00:00 [queued]>
[2025-05-24T04:38:15.154+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: order_monitoring_dag1.run_dbt_models scheduled__2025-05-23T22:00:00+00:00 [queued]>
[2025-05-24T04:38:15.154+0530] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-24T04:38:15.163+0530] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-05-23 22:00:00+00:00
[2025-05-24T04:38:15.174+0530] {logging_mixin.py:188} WARNING - /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=16167) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-24T04:38:15.175+0530] {standard_task_runner.py:63} INFO - Started process 16170 to run task
[2025-05-24T04:38:15.174+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'order_monitoring_dag1', 'run_dbt_models', 'scheduled__2025-05-23T22:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/order_monitoring_dag.py', '--cfg-path', '/var/folders/7w/779kl2wj7p9971zq3yv085jm0000gn/T/tmprj_0y31c']
[2025-05-24T04:38:15.177+0530] {standard_task_runner.py:91} INFO - Job 6: Subtask run_dbt_models
[2025-05-24T04:38:15.217+0530] {task_command.py:426} INFO - Running <TaskInstance: order_monitoring_dag1.run_dbt_models scheduled__2025-05-23T22:00:00+00:00 [running]> on host zafars-macbook-pro.local
[2025-05-24T04:38:15.269+0530] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='order_monitoring_dag1' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-23T22:00:00+00:00'
[2025-05-24T04:38:15.271+0530] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-24T04:38:15.271+0530] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/7w/779kl2wj7p9971zq3yv085jm0000gn/T
[2025-05-24T04:38:15.272+0530] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd "/Users/zafarimam/Documents/E-Commerce Order Pipeline/dbt_ecommerce" && dbt run']
[2025-05-24T04:38:15.278+0530] {subprocess.py:86} INFO - Output:
[2025-05-24T04:38:16.651+0530] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-24T04:38:16.652+0530] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.12/bin/dbt", line 5, in <module>
[2025-05-24T04:38:16.653+0530] {subprocess.py:93} INFO -     from dbt.cli.main import cli
[2025-05-24T04:38:16.653+0530] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/cli/__init__.py", line 1, in <module>
[2025-05-24T04:38:16.653+0530] {subprocess.py:93} INFO -     from .main import cli as dbt_cli  # noqa
[2025-05-24T04:38:16.654+0530] {subprocess.py:93} INFO -     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-24T04:38:16.654+0530] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/cli/main.py", line 13, in <module>
[2025-05-24T04:38:16.655+0530] {subprocess.py:93} INFO -     from dbt.artifacts.schemas.run import RunExecutionResult
[2025-05-24T04:38:16.655+0530] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/artifacts/schemas/run/__init__.py", line 2, in <module>
[2025-05-24T04:38:16.656+0530] {subprocess.py:93} INFO -     from dbt.artifacts.schemas.run.v5.run import *  # noqa
[2025-05-24T04:38:16.656+0530] {subprocess.py:93} INFO -     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-24T04:38:16.657+0530] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/artifacts/schemas/run/v5/run.py", line 23, in <module>
[2025-05-24T04:38:16.657+0530] {subprocess.py:93} INFO -     from dbt.artifacts.schemas.results import (
[2025-05-24T04:38:16.657+0530] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/artifacts/schemas/results.py", line 5, in <module>
[2025-05-24T04:38:16.658+0530] {subprocess.py:93} INFO -     from dbt.contracts.graph.nodes import ResultNode
[2025-05-24T04:38:16.658+0530] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/contracts/graph/nodes.py", line 67, in <module>
[2025-05-24T04:38:16.659+0530] {subprocess.py:93} INFO -     from dbt.contracts.graph.unparsed import (
[2025-05-24T04:38:16.659+0530] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/contracts/graph/unparsed.py", line 9, in <module>
[2025-05-24T04:38:16.660+0530] {subprocess.py:93} INFO -     from dbt import deprecations
[2025-05-24T04:38:16.660+0530] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/deprecations.py", line 4, in <module>
[2025-05-24T04:38:16.661+0530] {subprocess.py:93} INFO -     import dbt.tracking
[2025-05-24T04:38:16.661+0530] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/tracking.py", line 20, in <module>
[2025-05-24T04:38:16.661+0530] {subprocess.py:93} INFO -     from dbt.events.types import (
[2025-05-24T04:38:16.662+0530] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/events/__init__.py", line 4, in <module>
[2025-05-24T04:38:16.662+0530] {subprocess.py:93} INFO -     import dbt.events.types as core_dbt_event_types
[2025-05-24T04:38:16.663+0530] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/events/types.py", line 4, in <module>
[2025-05-24T04:38:16.663+0530] {subprocess.py:93} INFO -     from dbt.events.base_types import (
[2025-05-24T04:38:16.664+0530] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/events/base_types.py", line 2, in <module>
[2025-05-24T04:38:16.664+0530] {subprocess.py:93} INFO -     from dbt.events import core_types_pb2
[2025-05-24T04:38:16.664+0530] {subprocess.py:93} INFO -   File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/events/core_types_pb2.py", line 9, in <module>
[2025-05-24T04:38:16.665+0530] {subprocess.py:93} INFO -     from google.protobuf import runtime_version as _runtime_version
[2025-05-24T04:38:16.665+0530] {subprocess.py:93} INFO - ImportError: cannot import name 'runtime_version' from 'google.protobuf' (/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/google/protobuf/__init__.py)
[2025-05-24T04:38:16.755+0530] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-24T04:38:16.756+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-24T04:38:16.763+0530] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-24T04:38:16.772+0530] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=order_monitoring_dag1, task_id=run_dbt_models, execution_date=20250523T220000, start_date=20250523T230815, end_date=20250523T230816
[2025-05-24T04:38:16.781+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 1.; 16170)
[2025-05-24T04:38:16.817+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-24T04:38:16.835+0530] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-24T04:38:16.840+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
